### ISSUE TITLE
Hacer que el teléfono sea un campo numérico y el form acepte sólo números

### ISSUE THREAD

**Issue by FranciscoMontiron** [Fedebravo12/vetsoft#31]
## Validación del `phone`

#Hacer que el `phone` sea un campo numérico y que el formulario acepte solo números

- [x] Agregar la validación al formulario para que `phone` solo acepte números
- [x] Actualizar la interfaz para que aparezca el error en caso de que `phone` no sea numérico
- [x] Validar que no se pueda cargar un número de teléfono que no cumpla con la nueva regla
- [x] Crear pruebas unitarias para validar la funcionalidad
- [x] Crear pruebas de integración
- [x] Crear pruebas end-to-end (e2e)

**Comment by brunolopezv** [comment]
Buenas, se entrega el pr con todo lo solicitado en la issue.
